//! Shared pipeline definition for the sales_run, sales_viz, and sales_app examples.
//!
//! All examples use the same sales pipeline and types; only the subcommand
//! they invoke (`run` vs `viz`) differs.

use plotly::{Bar, Layout, Plot};
use polars::prelude::*;
use serde::{Deserialize, Serialize};

use pondrs::datasets::{MemoryDataset, Param, PolarsCsvDataset, PlotlyDataset};
use pondrs::error::PondError;
use pondrs::{Node, Steps};

// ANCHOR: types
// ---------------------------------------------------------------------------
// Catalog and params
// ---------------------------------------------------------------------------

#[derive(Serialize, Deserialize)]
pub struct SalesCatalog {
    pub raw_sales: PolarsCsvDataset,
    pub filtered_sales: PolarsCsvDataset,
    pub total_sales: MemoryDataset<i64>,
    pub chart: PlotlyDataset,
}

#[derive(Serialize, Deserialize)]
pub struct SalesParams {
    /// Minimum sales to include a month in the chart.
    pub min_sales: Param<i64>,
}

// ANCHOR_END: types

// ANCHOR: nodes
// ---------------------------------------------------------------------------
// Node functions
// ---------------------------------------------------------------------------

fn build_chart(df: DataFrame, total: i64) -> (Plot,) {
    let months: Vec<String> = df
        .column("month").unwrap()
        .str().unwrap()
        .into_no_null_iter()
        .map(|s| s.to_string())
        .collect();
    let sales: Vec<i64> = df
        .column("sales").unwrap()
        .i64().unwrap()
        .into_no_null_iter()
        .collect();

    let mut plot = Plot::new();
    plot.add_trace(Bar::new(months, sales).name("Monthly Sales"));
    plot.set_layout(
        Layout::new()
            .title(format!("Months with sales ≥ 1000  (total: {total})"))
            .y_axis(plotly::layout::Axis::new().title("Sales")),
    );
    (plot,)
}

// ANCHOR_END: nodes

// ANCHOR: pipeline
// ---------------------------------------------------------------------------
// Pipeline function
// ---------------------------------------------------------------------------

pub fn sales_pipeline<'a>(
    cat: &'a SalesCatalog,
    params: &'a SalesParams,
) -> impl Steps<PondError> + 'a {
    (
        // Node 1: filter out months below the threshold
        Node {
            name: "filter_months",
            func: |df: DataFrame, min_sales: i64| -> Result<(DataFrame,), PolarsError> {
                let mask = df.column("sales")?.i64()?.gt_eq(min_sales);
                Ok((df.filter(&mask)?,))
            },
            input: (&cat.raw_sales, &params.min_sales),
            output: (&cat.filtered_sales,),
        },
        // Node 2: sum the filtered sales
        Node {
            name: "compute_total",
            func: |df: DataFrame| {
                let total =
                    df.column("sales").unwrap().i64().unwrap().sum().unwrap_or(0);
                (total,)
            },
            input: (&cat.filtered_sales,),
            output: (&cat.total_sales,),
        },
        // Node 3: build a bar chart of the filtered monthly sales
        Node {
            name: "build_chart",
            func: build_chart,
            input: (&cat.filtered_sales, &cat.total_sales),
            output: (&cat.chart,),
        },
    )
}

// ANCHOR_END: pipeline

// ---------------------------------------------------------------------------
// Shared fixture helpers
// ---------------------------------------------------------------------------

/// Fixed output directory for examples, relative to the workspace root.
/// Both viz_example and plotly_example use the same paths so the viz server
/// can serve previews generated by a subsequent `plotly_example` run.
pub fn examples_data_dir() -> std::path::PathBuf {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest.join("examples").join("data")
}

/// Write the sample CSV, catalog YAML, and params YAML into `dir`.
pub fn write_fixtures(dir: &std::path::Path) {
    use std::fs;

    fs::create_dir_all(dir).unwrap();

    fs::write(
        dir.join("monthly_sales.csv"),
        "\
month,sales
Jan,1200
Feb,800
Mar,1500
Apr,600
May,1800
Jun,950
Jul,2100
Aug,700
Sep,1600
Oct,1300
Nov,400
Dec,2200
",
    )
    .unwrap();

    fs::write(
        dir.join("catalog.yml"),
        format!(
            "\
raw_sales:
  path: {d}/monthly_sales.csv
filtered_sales:
  path: {d}/filtered_sales.csv
total_sales: {{}}
chart:
  path: {d}/sales_chart.json
",
            d = dir.display()
        ),
    )
    .unwrap();

    fs::write(dir.join("params.yml"), "min_sales: 1000\n").unwrap();
}
